-- ============================================
-- Migration 007 — seed bilingual blog posts (dev/test content)
-- Idempotent — uses ON CONFLICT DO NOTHING on the unique slug.
-- ============================================

INSERT INTO public.blog_posts
    (slug, title_fr, title_ar, excerpt_fr, excerpt_ar, content_fr, content_ar,
     cover_image_url, category, reading_time_minutes, author_name)
VALUES
(
    'irrigation-goutte-a-goutte-economie-eau',
    'Comment économiser l''eau avec l''irrigation au goutte-à-goutte',
    'كيف توفر الماء بالري بالتنقيط',
    'L''irrigation au goutte-à-goutte peut réduire votre consommation d''eau de 40% à 60% par rapport aux méthodes traditionnelles.',
    'يمكن للري بالتنقيط أن يقلل استهلاكك للماء بنسبة 40 إلى 60 بالمائة مقارنة بالطرق التقليدية.',
    E'## Pourquoi le goutte-à-goutte ?\n\nDans un pays où l''eau devient une ressource rare, choisir la bonne méthode d''irrigation n''est plus un détail technique — c''est une décision économique majeure. Le goutte-à-goutte délivre l''eau directement à la zone racinaire de chaque plante, à un débit lent et contrôlé.\n\nRésultat : **90% de l''eau atteint réellement la culture**, contre 55% à 75% pour les méthodes par aspersion ou par gravité.\n\n## Combien ça coûte vraiment ?\n\nUn système simple pour 500 m² peut être installé pour 4 000 à 8 000 DH selon la qualité des composants. À condition de bien le dimensionner, l''investissement est amorti en **2 à 3 saisons** grâce aux économies d''eau, d''engrais et de main-d''œuvre.\n\n## Les erreurs à éviter\n\n1. **Sous-dimensionner la pompe** : si votre pompe ne fournit pas assez de débit pour tous les goutteurs, certaines zones reçoivent moins d''eau que d''autres. Vérifiez toujours que le débit total des goutteurs (nombre × débit unitaire) ne dépasse pas la capacité de la pompe.\n2. **Oublier la filtration** : les goutteurs se bouchent vite si l''eau contient du sable ou de la matière organique. Installez un filtre à tamis ou à disques.\n3. **Espacer les goutteurs au hasard** : référez-vous au système racinaire de votre culture. Pour la tomate, 30 à 40 cm est un bon départ.\n\n## Le calcul rapide\n\nUtilisez le calculateur de cette application pour estimer en quelques secondes :\n- la quantité d''eau journalière nécessaire (en litres),\n- la durée d''arrosage optimale,\n- l''économie réalisée par rapport au gravitaire.\n\nN''oubliez pas : la meilleure technologie ne remplace pas l''observation quotidienne du sol et des plantes.',
    E'## لماذا الري بالتنقيط؟\n\nفي بلد أصبح فيه الماء موردًا نادرًا، لم يعد اختيار طريقة الري مجرد تفصيل تقني — إنه قرار اقتصادي مهم. يوصل الري بالتنقيط الماء مباشرة إلى منطقة جذور كل نبتة، بتدفق بطيء ومنضبط.\n\nالنتيجة: **90% من الماء يصل فعلًا إلى المحصول**، مقابل 55% إلى 75% لطرق الرش أو الجاذبية.\n\n## كم يكلف فعليًا؟\n\nيمكن تركيب نظام بسيط لمساحة 500 متر مربع بمبلغ 4000 إلى 8000 درهم حسب جودة المكونات. إذا أحسنت التصميم، يتم استرداد الاستثمار في **موسمين إلى ثلاثة مواسم** بفضل توفير الماء والسماد واليد العاملة.\n\n## أخطاء يجب تجنبها\n\n1. **مضخة غير كافية**: إذا كانت مضختك لا توفر تدفقًا كافيًا لجميع القطّارات، تتلقى بعض المناطق ماءً أقل من غيرها. تحقق دائمًا من أن إجمالي تدفق القطّارات (عدد × التدفق الفردي) لا يتجاوز سعة المضخة.\n2. **نسيان الترشيح**: تنسد القطّارات بسرعة إذا كان الماء يحتوي على رمل أو مواد عضوية. ركّب فلترًا شبكيًا أو قرصيًا.\n3. **توزيع القطّارات عشوائيًا**: راجع نظام جذور محصولك. للطماطم، 30 إلى 40 سم نقطة بداية جيدة.\n\n## الحساب السريع\n\nاستخدم حاسبة هذا التطبيق لتقدير في ثوانٍ:\n- كمية الماء اليومية المطلوبة (باللتر)،\n- المدة المثلى للري،\n- التوفير المحقق مقارنة بالري السطحي.\n\nلا تنسَ: أفضل تقنية لا تعوّض المراقبة اليومية للتربة والنباتات.',
    'https://images.unsplash.com/photo-1601651074005-21a5e8c70a99?w=1200&q=80',
    'irrigation',
    6,
    'Smart Irrigation Team'
),
(
    'detecter-maladies-feuilles-tomate',
    'Détecter les maladies du tomate avant qu''il ne soit trop tard',
    'كيف تكتشف أمراض الطماطم قبل فوات الأوان',
    'Le mildiou, l''oïdium et les taches bactériennes peuvent détruire une récolte en quelques jours. Reconnaissez-les tôt.',
    'يمكن للفطريات والبكتيريا أن تتلف محصول الطماطم في أيام قليلة. تعلّم اكتشافها مبكرًا.',
    E'## Le mildiou : l''ennemi public n°1\n\nLe mildiou de la tomate (*Phytophthora infestans*) apparaît typiquement après une période humide avec des températures entre 15 et 25°C. Les premiers symptômes :\n- taches huileuses, brun-grisâtre sur les feuilles supérieures,\n- duvet blanchâtre sous les feuilles,\n- les tiges noircissent rapidement.\n\n**Si vous voyez ces signes, agissez dans les 24 heures.** Le mildiou peut détruire un champ entier en moins d''une semaine. Pulvérisez du mancozèbe ou du métalaxyl, supprimez les plants gravement atteints.\n\n## L''alternariose : moins spectaculaire, mais aussi destructrice\n\nL''alternariose (taches noires concentriques) attaque d''abord les feuilles du bas. Elle progresse lentement mais affaiblit la plante. Traitement : fongicide à base de chlorothalonil + paillage du sol.\n\n## Le virus TYLCV\n\nTransmis par l''aleurode (mouche blanche), ce virus n''a **aucun traitement curatif**. Les feuilles s''enroulent et jaunissent, la plante reste rabougrie. La seule défense : arracher les plants infectés et lutter contre la mouche blanche dès son apparition.\n\n## Utilisez la détection par image\n\nL''application embarque un modèle d''IA capable de reconnaître 38 maladies de plantes à partir d''une simple photo de feuille. Précision sur photos de terrain : ~50% top-1, 82% top-5 — autrement dit, dans 4 cas sur 5 la bonne maladie figure parmi les 5 hypothèses du modèle.\n\nLa règle d''or : si le modèle hésite (faible confiance), prenez une photo plus nette et croisez avec un avis d''agronome avant de traiter.',
    E'## اللفحة المتأخرة: العدو الأول\n\nتظهر اللفحة المتأخرة للطماطم (*Phytophthora infestans*) عادة بعد فترة رطوبة مع درجات حرارة بين 15 و 25 مئوية. الأعراض الأولى:\n- بقع زيتية بنية رمادية على الأوراق العلوية،\n- زغب أبيض تحت الأوراق،\n- اسوداد السيقان بسرعة.\n\n**إذا رأيت هذه العلامات، تصرّف خلال 24 ساعة.** يمكن للفطر أن يدمر حقلًا كاملًا في أقل من أسبوع. رش المانكوزيب أو الميتالاكسيل، وأزل النباتات شديدة الإصابة.\n\n## اللفحة المبكرة: أقل لفتًا لكن مدمرة كذلك\n\nتهاجم اللفحة المبكرة (بقع سوداء متحدة المركز) الأوراق السفلى أولًا. تتقدم ببطء لكنها تضعف النبتة. العلاج: مبيد فطري كلوروثالونيل + تغطية التربة.\n\n## فيروس TYLCV\n\nينقله الذبابة البيضاء، **ولا يوجد له علاج شافٍ**. تتجعد الأوراق وتصفر، ويبقى النبات قزمًا. الدفاع الوحيد: اقلع النباتات المصابة وحارب الذبابة البيضاء عند ظهورها.\n\n## استخدم الكشف بالصورة\n\nيتضمن التطبيق نموذج ذكاء اصطناعي يستطيع التعرف على 38 مرضًا من صورة بسيطة لورقة. الدقة على صور الميدان: ~50% الأعلى، 82% ضمن الخمسة الأولى — أي أن المرض الصحيح يظهر ضمن فرضيات النموذج الخمس في 4 حالات من أصل 5.\n\nالقاعدة الذهبية: إذا تردد النموذج (ثقة منخفضة)، التقط صورة أوضح واستشر مهندسًا زراعيًا قبل العلاج.',
    'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=1200&q=80',
    'disease',
    7,
    'Smart Irrigation Team'
),
(
    'calendrier-irrigation-maroc-meteo',
    'Planifier son calendrier d''irrigation selon la météo marocaine',
    'تخطيط جدول الري حسب المناخ المغربي',
    'Le climat varie énormément entre Tanger et Ouarzazate. Adaptez votre fréquence d''arrosage aux conditions réelles.',
    'يتباين المناخ بشكل كبير بين طنجة وورزازات. كيّف وتيرة الري حسب الظروف الفعلية.',
    E'## Les trois climats du Maroc agricole\n\nLe Maroc agricole se divise en trois grandes zones :\n- **Côte atlantique nord** (Tanger, Kénitra, Rabat) : climat méditerranéen humide. Pluies fréquentes en automne et hiver, ETo modérée (~3-5 mm/jour en été).\n- **Plaines intérieures** (Marrakech, Meknès, Fès) : climat continental. Étés très chauds (ETo 7-9 mm/jour en juillet), hivers froids et secs.\n- **Sud présaharien** (Ouarzazate, Errachidia) : climat aride. ETo dépasse 10 mm/jour en été, précipitations rares.\n\n## La règle FAO-56 simplifiée\n\nLe besoin en eau quotidien d''une culture s''écrit :\n\n> **ETc = ETo × Kc**\n\noù **Kc** est le coefficient cultural (variable selon la culture et son stade) et **ETo** est l''évapotranspiration de référence (variable selon la météo locale).\n\nExemple pour une tomate en plein été à Marrakech :\n- ETo ≈ 8 mm/jour\n- Kc en mi-saison ≈ 1,15\n- ETc ≈ 9,2 mm/jour\n\nSur 500 m² avec un système au goutte-à-goutte (efficacité 90%), il faut donc apporter :\n\n> 9,2 ÷ 0,90 × 500 = **5 110 litres par jour**\n\n## Le rôle de la pluie\n\nSeule 70% à 80% de la pluie est réellement utile (le reste s''évapore ou ruisselle). Sur une journée pluvieuse à 10 mm, attendez-vous à 7-8 mm d''eau effectivement disponible pour vos plantes — soit l''équivalent d''une journée d''irrigation complète pour la plupart des cultures.\n\n## Surveillez les vagues de chaleur\n\nQuand 5 jours consécutifs dépassent 35°C, le stress hydrique devient critique. L''application déclenche alors une alerte rouge et recommande de fractionner l''arrosage en deux passes (matin et soir) pour limiter l''évaporation.',
    E'## ثلاثة مناخات للزراعة المغربية\n\nتنقسم المنطقة الزراعية المغربية إلى ثلاث مناطق كبرى:\n- **الساحل الأطلسي الشمالي** (طنجة، القنيطرة، الرباط): مناخ متوسطي رطب. أمطار متكررة في الخريف والشتاء، تبخر-نتح معتدل (~3-5 مم/يوم في الصيف).\n- **السهول الداخلية** (مراكش، مكناس، فاس): مناخ قاري. صيف حار جدًا (ETo 7-9 مم/يوم في يوليوز)، شتاء بارد وجاف.\n- **الجنوب شبه الصحراوي** (ورزازات، الراشيدية): مناخ جاف. يتجاوز التبخر 10 مم/يوم في الصيف، الأمطار نادرة.\n\n## قاعدة FAO-56 المبسطة\n\nتُكتب الحاجة اليومية للماء لمحصول كالتالي:\n\n> **ETc = ETo × Kc**\n\nحيث **Kc** هو معامل المحصول (يتغير حسب النوع والمرحلة) و **ETo** هو التبخر-النتح المرجعي (يتغير حسب الطقس المحلي).\n\nمثال لطماطم في صيف مراكش:\n- ETo ≈ 8 مم/يوم\n- Kc في منتصف الموسم ≈ 1.15\n- ETc ≈ 9.2 مم/يوم\n\nعلى مساحة 500 م² بنظام تنقيط (كفاءة 90%)، يجب توفير:\n\n> 9.2 ÷ 0.90 × 500 = **5,110 لتر يوميًا**\n\n## دور المطر\n\nفقط 70% إلى 80% من المطر مفيد فعليًا (الباقي يتبخر أو يجري). في يوم ممطر بـ 10 مم، توقّع 7-8 مم من الماء المتاح فعلًا لنباتاتك — وهو ما يعادل يوم ري كامل لمعظم المحاصيل.\n\n## راقب موجات الحرارة\n\nعندما تتجاوز 5 أيام متتالية درجة 35 مئوية، يصبح الإجهاد المائي حرجًا. يطلق التطبيق تنبيهًا أحمر ويوصي بتقسيم الري إلى مرتين (صباحًا ومساءً) للحد من التبخر.',
    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    'planning',
    8,
    'Smart Irrigation Team'
)
ON CONFLICT (slug) DO NOTHING;
